import type React from "react";

const branchBatch = {
  bbView: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column" as const,
    gap: 12,
    overflow: "auto",
    padding: 16,
  },
  bbHeader: {
    display: "flex",
    alignItems: "center" as const,
    gap: 10,
  },
  bbTitle: {
    fontSize: 16,
    fontWeight: 800,
    color: "var(--text-primary)",
  },
  bbBackBtn: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: 6,
    height: 30,
    padding: "0 10px",
    borderRadius: 8,
    border: "1px solid var(--border-medium)",
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 12,
    cursor: "pointer",
  },
  bbBtnPrimary: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: 6,
    height: 32,
    padding: "0 14px",
    borderRadius: 8,
    border: "1px solid var(--accent)",
    background: "var(--accent)",
    color: "var(--fg-on-accent)",
    fontSize: 12.5,
    fontWeight: 700,
    cursor: "pointer",
  },
  bbBtnGhost: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: 6,
    height: 30,
    padding: "0 10px",
    borderRadius: 8,
    border: "1px solid var(--border-dim)",
    background: "transparent",
    color: "var(--text-muted)",
    fontSize: 12,
    cursor: "pointer",
  },
  bbList: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 10,
  },
  bbCard: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    borderRadius: 12,
    padding: 14,
  },
  bbCardHead: {
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
  },
  bbCardTitle: {
    fontSize: 13.5,
    fontWeight: 700,
    color: "var(--text-primary)",
  },
  bbCardMono: {
    fontFamily: "var(--font-mono)",
    fontSize: 11.5,
    color: "var(--text-secondary)",
  },
  bbCardSub: {
    display: "flex",
    alignItems: "center" as const,
    gap: 12,
    marginTop: 8,
    color: "var(--text-hint)",
    fontSize: 11.5,
  },
  bbCardActions: {
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
    marginTop: 12,
  },
  bbBadge: {
    fontSize: 10.5,
    fontWeight: 700,
    borderRadius: 6,
    padding: "1px 7px",
    border: "1px solid var(--border-medium)",
    color: "var(--text-secondary)",
  },
  bbBadgeActive: {
    background: "var(--accent-subtle)",
    color: "var(--accent)",
    borderColor: "var(--accent-soft)",
  },
  bbBadgeConflict: {
    background: "rgba(248,81,73,.14)",
    color: "var(--danger-fg)",
    borderColor: "rgba(248,81,73,.34)",
  },
  bbBadgeDone: {
    background: "rgba(74,222,128,.12)",
    color: "var(--success-fg)",
    borderColor: "rgba(74,222,128,.34)",
  },
  bbMetric: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: 4,
  },
  bbEmpty: {
    padding: "48px 0",
    textAlign: "center" as const,
    color: "var(--text-hint)",
    fontSize: 13,
  },
  bbDialogOverlay: {
    position: "fixed" as const,
    inset: 0,
    background: "var(--overlay-bg)",
    display: "flex",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    zIndex: 2000,
  },
  bbDialog: {
    width: 520,
    maxWidth: "92vw",
    maxHeight: "86vh",
    overflow: "auto",
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 14,
    boxShadow: "var(--shadow-popover)",
    padding: 18,
  },
  bbDialogTitle: {
    fontSize: 14,
    fontWeight: 800,
    marginBottom: 14,
  },
  bbField: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 6,
    marginBottom: 12,
  },
  bbFieldLabel: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-secondary)",
  },
  bbInput: {
    height: 32,
    padding: "0 10px",
    borderRadius: 8,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontSize: 13,
    outline: "none",
  },
  bbOptionGrid: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: 8,
  },
  bbOptionBtn: {
    height: 26,
    padding: "0 10px",
    borderRadius: 6,
    border: "1px solid var(--border-medium)",
    background: "transparent",
    color: "var(--text-muted)",
    fontSize: 12,
    cursor: "pointer",
  },
  bbOptionBtnActive: {
    height: 26,
    padding: "0 10px",
    borderRadius: 6,
    border: "1px solid var(--accent-soft)",
    background: "var(--accent-subtle)",
    color: "var(--accent)",
    borderColor: "var(--accent-soft)",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  bbMemberList: {
    maxHeight: 160,
    overflow: "auto",
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    padding: 6,
  },
  bbMember: {
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
    fontSize: 12.5,
    padding: "4px 6px",
    borderRadius: 6,
    color: "var(--text-secondary)",
  },
  bbDialogActions: {
    display: "flex",
    justifyContent: "flex-end" as const,
    gap: 8,
    marginTop: 16,
  },
  bbError: {
    display: "inline-block",
    marginBottom: 8,
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 6,
    padding: "1px 7px",
    border: "1px solid rgba(248,81,73,.34)",
    background: "rgba(248,81,73,.14)",
    color: "var(--danger-fg)",
  },
  bbFill: {
    flex: 1,
  },
  bbDiffOverlay: {
    position: "fixed" as const,
    inset: 0,
    background: "var(--overlay-bg)",
    display: "flex",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    zIndex: 2000,
  },
  bbDiffDialog: {
    width: 920,
    maxWidth: "94vw",
    height: "82vh",
    display: "flex",
    flexDirection: "column" as const,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 14,
    boxShadow: "var(--shadow-popover)",
    overflow: "hidden",
  },
  bbDiffHead: {
    display: "flex",
    alignItems: "center" as const,
    gap: 10,
    padding: "10px 14px",
    borderBottom: "1px solid var(--border-dim)",
    color: "var(--text-secondary)",
    fontSize: 12.5,
  },
  bbDiffBody: {
    flex: 1,
    display: "flex",
    minHeight: 0,
  },
  bbDiffFiles: {
    width: 300,
    borderRight: "1px solid var(--border-dim)",
    overflow: "auto",
    padding: 8,
  },
  bbDiffFile: {
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
    padding: "6px 8px",
    borderRadius: 8,
    fontSize: 12,
    color: "var(--text-secondary)",
    cursor: "pointer",
  },
  bbDiffFileActive: {
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
    padding: "6px 8px",
    borderRadius: 8,
    fontSize: 12,
    color: "var(--text-secondary)",
    cursor: "pointer",
    background: "var(--bg-hover)",
  },
  bbDiffPane: {
    flex: 1,
    overflow: "auto",
    padding: 10,
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    lineHeight: 1.55,
  },
  bbDiffLine: {
    display: "block",
    whiteSpace: "pre" as const,
    color: "var(--text-secondary)",
  },
  bbDiffGutter: {
    width: 18,
    textAlign: "right" as const,
    color: "var(--text-hint)",
    display: "inline-block",
    marginRight: 8,
  },
  bbDiffLineAdd: {
    display: "block",
    whiteSpace: "pre" as const,
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    lineHeight: 1.55,
    background: "rgba(74,222,128,.12)",
    color: "var(--success-fg)",
  },
  bbDiffLineDel: {
    display: "block",
    whiteSpace: "pre" as const,
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    lineHeight: 1.55,
    background: "rgba(248,113,113,.12)",
    color: "var(--danger-fg)",
  },
  bbDiffHunk: {
    display: "block",
    whiteSpace: "pre" as const,
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    lineHeight: 1.55,
    color: "var(--text-muted)",
    background: "var(--bg-subtle)",
  },
  bbToolbar: {
    padding: 12,
    display: "flex",
    gap: 8,
    alignItems: "center" as const,
  },
  bbSourceInput: {
    height: 32,
    padding: "0 10px",
    borderRadius: 8,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontSize: 13,
    outline: "none",
    width: 220,
  },
  bbSection: {
    marginTop: 12,
  },
  bbReviewRules: {
    fontFamily: "var(--font-mono)",
    fontSize: 11.5,
    lineHeight: 1.6,
    whiteSpace: "pre-wrap" as const,
    background: "var(--bg-subtle)",
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    padding: 10,
    color: "var(--text-secondary)",
    maxHeight: 260,
    overflow: "auto",
  },
  bbGateHint: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: 6,
    fontSize: 12,
    color: "var(--warning)",
  },
  bbReviewBody: {
    padding: 14,
    overflow: "auto",
    display: "flex",
    gap: 16,
  },
  bbReviewCol: {
    flex: 1,
    minWidth: 0,
  },
  bbReviewSide: {
    width: 260,
  },
} satisfies Record<string, React.CSSProperties>;

export { branchBatch };
