import type React from "react";

export const build = {
  panelRoot: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    background: "var(--bg-panel, #1b1b1b)",
    overflow: "hidden",
  },
  header: {
    padding: "12px 14px 10px",
    borderBottom: "1px solid var(--border-dim, #2a2a2a)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: "var(--fg, #e6e6e6)",
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  scroll: {
    flex: 1,
    overflowY: "auto",
    padding: "12px 14px 20px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  card: {
    border: "1px solid var(--border-dim, #262626)",
    borderRadius: 10,
    background: "var(--bg-elevated, #202020)",
    padding: "10px 12px",
  },
  cardTitle: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--fg-muted, #9a9a9a)",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 8,
  },
  repoRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "5px 0",
    borderBottom: "1px solid var(--border-dim, #262626)",
  },
  repoName: {
    fontSize: 12,
    color: "var(--fg, #e6e6e6)",
    flex: 1,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  branchTrigger: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11,
    color: "var(--fg, #e6e6e6)",
    background: "var(--bg-panel, #161616)",
    border: "1px solid var(--border-dim, #2a2a2a)",
    borderRadius: 6,
    padding: "2px 8px",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  branchContent: {
    background: "var(--bg-elevated, #242424)",
    border: "1px solid var(--border-dim, #2a2a2a)",
    borderRadius: 8,
    overflow: "hidden",
    minWidth: 160,
    boxShadow: "0 6px 18px rgba(0,0,0,.35)",
  },
  branchItem: {
    fontSize: 12,
    color: "var(--fg, #e6e6e6)",
    padding: "6px 10px",
    cursor: "pointer",
    outline: "none",
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11,
    padding: "1px 7px",
    borderRadius: 999,
  },
  banner: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    fontSize: 12,
    color: "var(--fg, #e6e6e6)",
    padding: "8px 10px",
    border: "1px solid var(--border-dim, #2a2a2a)",
    borderRadius: 8,
    background: "var(--bg-elevated, #202020)",
  },
  segRow: {
    display: "flex",
    gap: 6,
  },
  segBtn: {
    flex: 1,
    padding: "6px 0",
    fontSize: 12,
    borderRadius: 6,
    border: "1px solid var(--border-dim, #2a2a2a)",
    background: "transparent",
    color: "var(--fg-muted, #9a9a9a)",
    cursor: "pointer",
  },
  segActive: {
    color: "var(--fg, #e6e6e6)",
    borderColor: "var(--accent, #4f8cff)",
    background: "rgba(79,140,255,.12)",
  },
  buttonRow: {
    display: "flex",
    gap: 8,
  },
  button: {
    flex: 1,
    padding: "7px 10px",
    fontSize: 12,
    borderRadius: 7,
    border: "1px solid var(--border-dim, #2a2a2a)",
    background: "var(--bg-panel, #161616)",
    color: "var(--fg, #e6e6e6)",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  buttonPrimary: {
    background: "var(--accent, #4f8cff)",
    color: "#fff",
    border: "1px solid transparent",
  },
  buttonDanger: {
    background: "var(--danger, #e5484d)",
    color: "#fff",
    border: "1px solid transparent",
  },
  buttonSmall: {
    padding: "4px 10px",
    fontSize: 12,
    borderRadius: 6,
    border: "1px solid var(--border-dim, #2a2a2a)",
    background: "var(--bg-panel, #161616)",
    color: "var(--fg, #e6e6e6)",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  statusLine: {
    fontSize: 12,
    color: "var(--fg, #e6e6e6)",
    padding: "3px 0",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  errText: {
    color: "var(--danger, #e5484d)",
  },
  okText: {
    color: "var(--success, #30a46c)",
  },
  warnText: {
    color: "var(--warning, #f5a623)",
  },
  meta: {
    fontSize: 11,
    color: "var(--fg-muted, #9a9a9a)",
  },
  stageGroup: {
    marginBottom: 8,
  },
  stageHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: 12,
    fontWeight: 600,
    color: "var(--fg, #e6e6e6)",
    padding: "4px 0",
  },
  projRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    color: "var(--fg-muted, #9a9a9a)",
    padding: "2px 0 2px 8px",
  },
  projDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    flexShrink: 0,
  },
  logBox: {
    border: "1px solid var(--border-dim, #2a2a2a)",
    borderRadius: 8,
    background: "var(--bg-panel, #111)",
    overflow: "hidden",
  },
  logScroll: {
    maxHeight: 220,
    overflowY: "auto",
    padding: "8px 10px",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 11,
    color: "var(--fg, #e6e6e6)",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  configField: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    marginBottom: 8,
  },
  configLabel: {
    fontSize: 11,
    color: "var(--fg-muted, #9a9a9a)",
  },
  configInput: {
    padding: "6px 8px",
    fontSize: 12,
    borderRadius: 7,
    border: "1px solid var(--border-dim, #2a2a2a)",
    background: "var(--bg-panel, #161616)",
    color: "var(--fg, #e6e6e6)",
  },
  fsRoot: {
    position: "fixed",
    inset: 0,
    zIndex: 2147483006,
    background: "var(--bg-app, #0d0d0d)",
    display: "flex",
    flexDirection: "column",
  },
  fsHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    padding: "10px 16px",
    borderBottom: "1px solid var(--border-dim, #262626)",
    background: "var(--bg-elevated, #161616)",
  },
  fsTitle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 14,
    fontWeight: 700,
    color: "var(--fg, #e6e6e6)",
  },
  fsBanner: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    fontSize: 12,
    color: "var(--fg, #e6e6e6)",
    flex: 1,
  },
  fsActions: {
    display: "flex",
    gap: 8,
    alignItems: "center",
  },
  fsBody: {
    flex: 1,
    display: "flex",
    gap: 12,
    padding: 12,
    overflow: "hidden",
  },
  fsLeft: {
    width: "46%",
    minWidth: 320,
    overflowY: "auto",
    paddingRight: 4,
  },
  fsRight: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    border: "1px solid var(--border-dim, #262626)",
    borderRadius: 10,
    background: "var(--bg-panel, #111)",
    overflow: "hidden",
  },
  fsLog: {
    flex: 1,
    overflowY: "auto",
    padding: "10px 12px",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    color: "var(--fg, #e6e6e6)",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  failedItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    color: "var(--danger, #e5484d)",
    padding: "3px 0",
  },
  failedItemInfo: {
    color: "var(--fg-muted, #9a9a9a)",
    fontSize: 11,
  },
  collapseBar: {
    position: "fixed",
    left: 0,
    right: 0,
    bottom: 0,
    height: 34,
    zIndex: 2147483007,
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "0 12px",
    background: "var(--bg-elevated, #1b1b1b)",
    borderTop: "1px solid var(--border-dim, #2a2a2a)",
    fontSize: 12,
    color: "var(--fg, #e6e6e6)",
  },
  collapseBarSpacer: {
    flex: 1,
  },
  progressText: {
    fontSize: 11,
    color: "var(--fg-muted, #9a9a9a)",
    marginTop: 8,
  },
  progressTrack: {
    height: 6,
    borderRadius: 999,
    background: "var(--border-dim, #2a2a2a)",
    overflow: "hidden",
    marginTop: 4,
  },
  progressFill: {
    height: "100%",
    background: "var(--accent, #4f8cff)",
    transition: "width .2s",
  },
} satisfies Record<string, React.CSSProperties>;
