import type React from "react";

/** 欢迎页「计划」视图样式——视觉规格对齐 mockup `delivery-plan-ui-v1.html`：
 *  chip＝中性底+语义色文字（4px 圆角）；按钮＝panel2 底+描边 6px 圆角，primary 实色；
 *  列表选中＝chip 底无描边；表格行 7px/8px；主题色一律映射到既有 CSS 变量
 *  （mockup --panel2/--chip→--bg-hover/--badge-muted-bg，--ok/--warn/--err→
 *  --success-fg/--warning/--danger-fg）。 */
const deliveryPlan = {
  dpRoot: {
    display: "flex" as const,
    flexDirection: "column" as const,
    // 撑满 welcomeMain 的剩余宽度：缺 flex:1 会被内容宽度收缩（不自适应全屏）。
    flex: 1,
    width: "100%",
    minWidth: 0,
    height: "100%",
    minHeight: 0,
  },
  dpBody: {
    display: "flex" as const,
    flex: 1,
    minHeight: 0,
  },
  dpSide: {
    display: "flex" as const,
    flexDirection: "column" as const,
    width: 220,
    borderRight: "1px solid var(--border-dim)",
    overflowY: "auto" as const,
    padding: "12px 8px",
    flexShrink: 0,
  },
  dpSideFilter: {
    marginBottom: 10,
    padding: "0 2px",
  },
  dpSideFooter: {
    marginTop: 10,
    padding: "0 2px",
  },
  dpListItem: {
    display: "block" as const,
    width: "100%",
    textAlign: "left" as const,
    padding: "6px 10px",
    borderRadius: 6,
    border: "none",
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
    marginBottom: 2,
    fontSize: 12,
  },
  // 选中态＝chip 底 + 正文色（mockup .item.on），整体完整定义避免 style 内拼接。
  dpListItemActive: {
    display: "block" as const,
    width: "100%",
    textAlign: "left" as const,
    padding: "6px 10px",
    borderRadius: 6,
    border: "none",
    background: "var(--badge-muted-bg)",
    color: "var(--text-primary)",
    cursor: "pointer",
    marginBottom: 2,
    fontSize: 12,
  },
  dpListItemBranch: {
    display: "block" as const,
    fontFamily: "var(--font-mono)",
    fontSize: 10,
    color: "var(--text-hint)",
    marginTop: 2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  /** 列表项首行：计划名（省略号）＋ 状态标识 chip。 */
  dpListItemTop: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: 6,
    width: "100%",
  },
  dpListItemName: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    textAlign: "left" as const,
  },
  dpMain: {
    flex: 1,
    minWidth: 0,
    overflowY: "auto" as const,
    padding: "14px 16px",
  },
  dpHead: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: 8,
    flexWrap: "wrap" as const,
    paddingBottom: 12,
    borderBottom: "1px solid var(--border-dim)",
    marginBottom: 12,
  },
  dpTitle: { fontSize: 15, fontWeight: 600, color: "var(--text-primary)" },
  dpBranchRow: {
    fontFamily: "var(--font-mono)",
    fontSize: 11.5,
    color: "var(--text-hint)",
    marginBottom: 8,
  },
  dpSummary: {
    display: "flex" as const,
    gap: 6,
    marginBottom: 12,
    flexWrap: "wrap" as const,
    alignItems: "center" as const,
  },
  // chip 基座（mockup .chip）：中性底、4px 圆角、11px；色调变体只换文字色。
  dpChip: {
    display: "inline-block" as const,
    borderRadius: 4,
    padding: "1px 7px",
    fontSize: 11,
    background: "var(--badge-muted-bg)",
    color: "var(--text-secondary)",
    marginRight: 4,
    whiteSpace: "nowrap" as const,
  },
  dpChipAc: {
    display: "inline-block" as const,
    borderRadius: 4,
    padding: "1px 7px",
    fontSize: 11,
    background: "var(--badge-muted-bg)",
    color: "var(--accent)",
    marginRight: 4,
    whiteSpace: "nowrap" as const,
  },
  dpChipOk: {
    display: "inline-block" as const,
    borderRadius: 4,
    padding: "1px 7px",
    fontSize: 11,
    background: "var(--badge-muted-bg)",
    color: "var(--success-fg)",
    marginRight: 4,
    whiteSpace: "nowrap" as const,
  },
  dpChipWarn: {
    display: "inline-block" as const,
    borderRadius: 4,
    padding: "1px 7px",
    fontSize: 11,
    background: "var(--badge-muted-bg)",
    color: "var(--warning)",
    marginRight: 4,
    whiteSpace: "nowrap" as const,
  },
  dpChipErr: {
    display: "inline-block" as const,
    borderRadius: 4,
    padding: "1px 7px",
    fontSize: 11,
    background: "var(--badge-muted-bg)",
    color: "var(--danger-fg)",
    marginRight: 4,
    whiteSpace: "nowrap" as const,
  },
  dpChipMono: {
    display: "inline-block" as const,
    borderRadius: 4,
    padding: "1px 7px",
    fontSize: 11,
    background: "var(--badge-muted-bg)",
    color: "var(--text-secondary)",
    fontFamily: "var(--font-mono)",
    marginRight: 4,
    whiteSpace: "nowrap" as const,
  },
  dpTable: { width: "100%", borderCollapse: "collapse" as const },
  dpTh: {
    textAlign: "left" as const,
    padding: "7px 8px",
    fontSize: 12.5,
    color: "var(--text-hint)",
    fontWeight: 500,
    borderBottom: "1px solid var(--border-dim)",
    // 表头都是短词（议题/状态/关联方案），窄面板下不许折行成「关联方/案」。
    whiteSpace: "nowrap" as const,
  },
  // 勾选列：窄列居中（表头与单元格共用），让勾选框与议题文字对齐。
  dpThCheck: {
    width: 28,
    padding: "7px 0 7px 6px",
    borderBottom: "1px solid var(--border-dim)",
    whiteSpace: "nowrap" as const,
  },
  dpTdCheck: {
    width: 28,
    padding: "7px 0 7px 6px",
    borderBottom: "1px solid var(--border-dim)",
    verticalAlign: "top" as const,
  },
  dpTd: {
    padding: "7px 8px",
    fontSize: 12.5,
    borderBottom: "1px solid var(--border-dim)",
    verticalAlign: "top" as const,
    color: "var(--text-primary)",
  },
  /** 议题单元格：编号 chip + 标题 + 云效链接按钮同行，标题可换行。 */
  dpIssueCell: {
    display: "flex" as const,
    alignItems: "flex-start" as const,
    gap: 6,
  },
  dpIssueSubject: {
    flex: 1,
    minWidth: 0,
    lineHeight: 1.5,
  },
  // 行内「在云效打开」：默认隐形，hover 行/按钮时才亮（避免每行多一个实心按钮抢视线）。
  dpIssueLinkBtn: {
    flexShrink: 0,
    display: "inline-flex" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    width: 22,
    height: 22,
    padding: 0,
    borderRadius: 5,
    border: "1px solid transparent",
    background: "transparent",
    color: "var(--text-hint)",
    cursor: "pointer",
    opacity: 0.55,
    transition: "background 0.12s, border-color 0.12s, color 0.12s, opacity 0.12s",
  },
  dpIssueLinkBtnHover: {
    flexShrink: 0,
    display: "inline-flex" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    width: 22,
    height: 22,
    padding: 0,
    borderRadius: 5,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-hover)",
    color: "var(--text-primary)",
    cursor: "pointer",
    opacity: 1,
    transition: "background 0.12s, border-color 0.12s, color 0.12s, opacity 0.12s",
  },
  /** 动作列：主操作＋「…」菜单贴右对齐（列窄，动作与正文拉开距离，静止态更安静）。 */
  dpTdActions: {
    padding: "7px 8px",
    fontSize: 12.5,
    borderBottom: "1px solid var(--border-dim)",
    verticalAlign: "top" as const,
    color: "var(--text-primary)",
    textAlign: "right" as const,
    whiteSpace: "nowrap" as const,
  },
  /** 多选动作条（贴在议题表上方）：与云效议题列表的底栏同语义，位置改顶部避免遮挡表尾。 */
  dpSelectBar: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: 8,
    padding: "6px 10px",
    marginBottom: 8,
    borderRadius: 8,
    border: "1px solid var(--border-dim)",
    background: "var(--bg-hover)",
  },
  dpSelectCount: {
    fontSize: 12,
    color: "var(--text-secondary)",
    fontVariantNumeric: "tabular-nums" as const,
  },
  dpEmpty: {
    color: "var(--text-hint)",
    fontSize: 12,
    textAlign: "center" as const,
    padding: "48px 16px",
    lineHeight: 2,
  },
  dpNotice: {
    color: "var(--danger-fg)",
    fontSize: 12,
    padding: "6px 16px",
  },
  dpHint: {
    color: "var(--text-hint)",
    fontSize: 11.5,
    marginTop: 8,
    lineHeight: 1.6,
  },
  // 按钮（mockup button）：panel2 底 + 描边 + 6px 圆角；primary 实色。
  dpBtn: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: 6,
    padding: "4px 12px",
    borderRadius: 6,
    border: "1px solid var(--border-dim)",
    background: "var(--bg-hover)",
    color: "var(--text-primary)",
    fontSize: 12,
    cursor: "pointer",
  },
  dpBtnPrimary: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: 6,
    padding: "4px 12px",
    borderRadius: 6,
    border: "1px solid var(--accent)",
    background: "var(--accent)",
    color: "var(--fg-on-accent)",
    fontSize: 12,
    cursor: "pointer",
  },
  dpBtnBlock: {
    display: "flex" as const,
    width: "100%",
    justifyContent: "center" as const,
  },
  // 侧栏「创建计划」：primary 通栏（完整定义，避免 style 内拼接对象）。
  dpBtnPrimaryBlock: {
    display: "flex" as const,
    width: "100%",
    justifyContent: "center" as const,
    alignItems: "center" as const,
    gap: 6,
    padding: "5px 12px",
    borderRadius: 6,
    border: "1px solid var(--accent)",
    background: "var(--accent)",
    color: "var(--fg-on-accent)",
    fontSize: 12,
    cursor: "pointer",
  },
  // 分支行里的「合并回目标分支」可编辑控件（空目标计划补记入口）。
  dpTargetBtn: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: 4,
    padding: "0 4px",
    border: "none",
    background: "transparent",
    color: "var(--text-hint)",
    fontFamily: "var(--font-mono)",
    fontSize: 11.5,
    cursor: "pointer",
  },
  // 未指定目标时强调「这里可点」：accent 文字 + 虚线底边，与普通灰字区分开。
  dpTargetBtnEmpty: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: 4,
    padding: "0 4px",
    border: "none",
    borderBottom: "1px dashed var(--accent)",
    background: "transparent",
    color: "var(--accent)",
    fontFamily: "var(--font-mono)",
    fontSize: 11.5,
    cursor: "pointer",
  },
  dpTargetEdit: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: 6,
  },
  dpTargetSelectTrigger: {
    minWidth: 140,
    height: 22,
    padding: "0 8px",
    borderRadius: 6,
    border: "1px solid var(--border-dim)",
    background: "var(--bg-hover)",
    color: "var(--text-primary)",
    fontSize: 11.5,
    fontFamily: "var(--font-mono)",
  },
  dpTargetError: {
    color: "var(--danger-fg)",
    fontSize: 11,
  },
  // 禁用按钮的悬停提示载体：disabled 的 button 不派发 hover，title 只能挂在包裹层上。
  dpBtnWrap: { display: "inline-flex" as const },
  dpSpacer: { flex: 1 },
} satisfies Record<string, React.CSSProperties>;

/** chip 色调 → 样式键（mockup .chip.ok/.warn/.err/.ac）。 */
const dpChipToneStyle = {
  neutral: deliveryPlan.dpChip,
  ac: deliveryPlan.dpChipAc,
  ok: deliveryPlan.dpChipOk,
  warn: deliveryPlan.dpChipWarn,
  err: deliveryPlan.dpChipErr,
} as const;

export { deliveryPlan, dpChipToneStyle };
