import type React from "react";

/** 欢迎页「计划」视图样式——视觉规格对齐 mockup `delivery-plan-ui-v1.html`：
 *  chip＝中性底+语义色文字（4px 圆角）；按钮＝panel2 底+描边 6px 圆角，primary 实色；
 *  列表选中＝chip 底无描边；表格行 7px/8px；主题色一律映射到既有 CSS 变量
 *  （mockup --panel2/--chip→--bg-hover/--badge-muted-bg，--ok/--warn/--err→
 *  --success-fg/--warning/--danger-fg）。 */
const deliveryPlan = {
  dpRoot: {
    display: "flex" as const,
    flexDirection: "column" as const,
    height: "100%",
    minHeight: 0,
  },
  dpBody: {
    display: "flex" as const,
    flex: 1,
    minHeight: 0,
  },
  dpSide: {
    display: "flex" as const,
    flexDirection: "column" as const,
    width: 220,
    borderRight: "1px solid var(--border-dim)",
    overflowY: "auto" as const,
    padding: "12px 8px",
    flexShrink: 0,
  },
  dpSideFilter: {
    marginBottom: 10,
    padding: "0 2px",
  },
  dpSideFooter: {
    marginTop: 10,
    padding: "0 2px",
  },
  dpListItem: {
    display: "block" as const,
    width: "100%",
    textAlign: "left" as const,
    padding: "6px 10px",
    borderRadius: 6,
    border: "none",
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
    marginBottom: 2,
    fontSize: 12,
  },
  // 选中态＝chip 底 + 正文色（mockup .item.on），整体完整定义避免 style 内拼接。
  dpListItemActive: {
    display: "block" as const,
    width: "100%",
    textAlign: "left" as const,
    padding: "6px 10px",
    borderRadius: 6,
    border: "none",
    background: "var(--badge-muted-bg)",
    color: "var(--text-primary)",
    cursor: "pointer",
    marginBottom: 2,
    fontSize: 12,
  },
  dpListItemBranch: {
    display: "block" as const,
    fontFamily: "var(--font-mono)",
    fontSize: 10,
    color: "var(--text-hint)",
    marginTop: 2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  dpMain: {
    flex: 1,
    minWidth: 0,
    overflowY: "auto" as const,
    padding: "14px 16px",
  },
  dpHead: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: 8,
    flexWrap: "wrap" as const,
    paddingBottom: 12,
    borderBottom: "1px solid var(--border-dim)",
    marginBottom: 12,
  },
  dpTitle: { fontSize: 15, fontWeight: 600, color: "var(--text-primary)" },
  dpBranchRow: {
    fontFamily: "var(--font-mono)",
    fontSize: 11.5,
    color: "var(--text-hint)",
    marginBottom: 8,
  },
  dpSummary: {
    display: "flex" as const,
    gap: 6,
    marginBottom: 12,
    flexWrap: "wrap" as const,
    alignItems: "center" as const,
  },
  // chip 基座（mockup .chip）：中性底、4px 圆角、11px；色调变体只换文字色。
  dpChip: {
    display: "inline-block" as const,
    borderRadius: 4,
    padding: "1px 7px",
    fontSize: 11,
    background: "var(--badge-muted-bg)",
    color: "var(--text-secondary)",
    marginRight: 4,
    whiteSpace: "nowrap" as const,
  },
  dpChipAc: {
    display: "inline-block" as const,
    borderRadius: 4,
    padding: "1px 7px",
    fontSize: 11,
    background: "var(--badge-muted-bg)",
    color: "var(--accent)",
    marginRight: 4,
    whiteSpace: "nowrap" as const,
  },
  dpChipOk: {
    display: "inline-block" as const,
    borderRadius: 4,
    padding: "1px 7px",
    fontSize: 11,
    background: "var(--badge-muted-bg)",
    color: "var(--success-fg)",
    marginRight: 4,
    whiteSpace: "nowrap" as const,
  },
  dpChipWarn: {
    display: "inline-block" as const,
    borderRadius: 4,
    padding: "1px 7px",
    fontSize: 11,
    background: "var(--badge-muted-bg)",
    color: "var(--warning)",
    marginRight: 4,
    whiteSpace: "nowrap" as const,
  },
  dpChipErr: {
    display: "inline-block" as const,
    borderRadius: 4,
    padding: "1px 7px",
    fontSize: 11,
    background: "var(--badge-muted-bg)",
    color: "var(--danger-fg)",
    marginRight: 4,
    whiteSpace: "nowrap" as const,
  },
  dpChipMono: {
    display: "inline-block" as const,
    borderRadius: 4,
    padding: "1px 7px",
    fontSize: 11,
    background: "var(--badge-muted-bg)",
    color: "var(--text-secondary)",
    fontFamily: "var(--font-mono)",
    marginRight: 4,
    whiteSpace: "nowrap" as const,
  },
  dpTable: { width: "100%", borderCollapse: "collapse" as const },
  dpTh: {
    textAlign: "left" as const,
    padding: "7px 8px",
    fontSize: 12.5,
    color: "var(--text-hint)",
    fontWeight: 500,
    borderBottom: "1px solid var(--border-dim)",
  },
  dpTd: {
    padding: "7px 8px",
    fontSize: 12.5,
    borderBottom: "1px solid var(--border-dim)",
    verticalAlign: "top" as const,
    color: "var(--text-primary)",
  },
  dpEmpty: {
    color: "var(--text-hint)",
    fontSize: 12,
    textAlign: "center" as const,
    padding: "48px 16px",
    lineHeight: 2,
  },
  dpNotice: {
    color: "var(--danger-fg)",
    fontSize: 12,
    padding: "6px 16px",
  },
  dpHint: {
    color: "var(--text-hint)",
    fontSize: 11.5,
    marginTop: 8,
    lineHeight: 1.6,
  },
  // 按钮（mockup button）：panel2 底 + 描边 + 6px 圆角；primary 实色。
  dpBtn: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: 6,
    padding: "4px 12px",
    borderRadius: 6,
    border: "1px solid var(--border-dim)",
    background: "var(--bg-hover)",
    color: "var(--text-primary)",
    fontSize: 12,
    cursor: "pointer",
  },
  dpBtnPrimary: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: 6,
    padding: "4px 12px",
    borderRadius: 6,
    border: "1px solid var(--accent)",
    background: "var(--accent)",
    color: "var(--fg-on-accent)",
    fontSize: 12,
    cursor: "pointer",
  },
  dpBtnBlock: {
    display: "flex" as const,
    width: "100%",
    justifyContent: "center" as const,
  },
  // 侧栏「创建计划」：primary 通栏（完整定义，避免 style 内拼接对象）。
  dpBtnPrimaryBlock: {
    display: "flex" as const,
    width: "100%",
    justifyContent: "center" as const,
    alignItems: "center" as const,
    gap: 6,
    padding: "5px 12px",
    borderRadius: 6,
    border: "1px solid var(--accent)",
    background: "var(--accent)",
    color: "var(--fg-on-accent)",
    fontSize: 12,
    cursor: "pointer",
  },
  dpSpacer: { flex: 1 },
} satisfies Record<string, React.CSSProperties>;

/** chip 色调 → 样式键（mockup .chip.ok/.warn/.err/.ac）。 */
const dpChipToneStyle = {
  neutral: deliveryPlan.dpChip,
  ac: deliveryPlan.dpChipAc,
  ok: deliveryPlan.dpChipOk,
  warn: deliveryPlan.dpChipWarn,
  err: deliveryPlan.dpChipErr,
} as const;

export { deliveryPlan, dpChipToneStyle };
