import type React from "react";

/** 欢迎页「计划」视图（列表＋详情）样式。主题色一律走 CSS 变量。 */
const deliveryPlan = {
  dpRoot: {
    display: "flex" as const,
    flexDirection: "column" as const,
    height: "100%",
    minHeight: 0,
  },
  dpToolbar: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: 10,
    padding: "12px 16px",
    borderBottom: "1px solid var(--border-subtle)",
    flexShrink: 0,
  },
  dpToolbarSelect: {
    height: 30,
    borderRadius: 8,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    fontSize: 12,
    padding: "0 8px",
  },
  dpBody: {
    display: "flex" as const,
    flex: 1,
    minHeight: 0,
  },
  dpSide: {
    width: 240,
    borderRight: "1px solid var(--border-subtle)",
    overflowY: "auto" as const,
    padding: 8,
    flexShrink: 0,
  },
  dpListItem: {
    display: "block" as const,
    width: "100%",
    textAlign: "left" as const,
    padding: "8px 10px",
    borderRadius: 8,
    border: "1px solid transparent",
    background: "transparent",
    color: "var(--text-primary)",
    cursor: "pointer",
    marginBottom: 4,
    fontSize: 12,
  },
  dpListItemActive: {
    border: "1px solid var(--accent)",
    background: "var(--bg-elevated)",
  },
  dpListItemBranch: {
    display: "block" as const,
    fontFamily: "var(--font-mono)",
    fontSize: 10.5,
    color: "var(--text-tertiary)",
    marginTop: 2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  dpMain: {
    flex: 1,
    minWidth: 0,
    overflowY: "auto" as const,
    padding: "14px 18px",
  },
  dpHead: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: 8,
    flexWrap: "wrap" as const,
    paddingBottom: 10,
    borderBottom: "1px solid var(--border-subtle)",
    marginBottom: 10,
  },
  dpTitle: { fontSize: 15, fontWeight: 600, color: "var(--text-primary)" },
  dpBranchRow: {
    fontFamily: "var(--font-mono)",
    fontSize: 11.5,
    color: "var(--text-tertiary)",
    marginBottom: 10,
  },
  dpSummary: { display: "flex" as const, gap: 6, marginBottom: 12, flexWrap: "wrap" as const },
  dpChip: {
    display: "inline-block" as const,
    borderRadius: 4,
    padding: "1px 7px",
    fontSize: 11,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-subtle)",
    color: "var(--text-secondary)",
  },
  dpChipMono: {
    display: "inline-block" as const,
    borderRadius: 4,
    padding: "1px 7px",
    fontSize: 11,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-subtle)",
    color: "var(--text-secondary)",
    fontFamily: "var(--font-mono)",
  },
  dpTable: { width: "100%", borderCollapse: "collapse" as const },
  dpTh: {
    textAlign: "left" as const,
    padding: "6px 8px",
    fontSize: 11.5,
    color: "var(--text-tertiary)",
    fontWeight: 500,
    borderBottom: "1px solid var(--border-subtle)",
  },
  dpTd: {
    padding: "8px",
    fontSize: 12,
    borderBottom: "1px solid var(--border-subtle)",
    verticalAlign: "top" as const,
  },
  dpEmpty: {
    color: "var(--text-tertiary)",
    fontSize: 12,
    textAlign: "center" as const,
    padding: "48px 16px",
  },
  dpBtn: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: 6,
    height: 30,
    padding: "0 12px",
    borderRadius: 8,
    border: "1px solid var(--border-medium)",
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 12,
    cursor: "pointer",
  },
  dpBtnPrimary: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: 6,
    height: 30,
    padding: "0 12px",
    borderRadius: 8,
    border: "1px solid var(--accent)",
    background: "var(--accent)",
    color: "#fff",
    fontSize: 12,
    cursor: "pointer",
  },
  dpSpacer: { flex: 1 },
} satisfies Record<string, React.CSSProperties>;

export { deliveryPlan };
