import type React from "react";

export const layout = {
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    background: "var(--bg-root)",
    overflow: "hidden",
  },
  rootRelative: {
    display: "flex",
    flexDirection: "column" as const,
    height: "100%",
    background: "var(--bg-root)",
    overflow: "hidden",
    position: "relative" as const,
  },
  appProjectLayer: {
    position: "absolute" as const,
    inset: 0,
    overflow: "hidden",
  },
  appWelcomeLayer: {
    position: "absolute" as const,
    inset: 0,
    zIndex: 5,
  },
  welcomeBody: {
    height: "100%",
    display: "flex",
    overflow: "hidden",
    background: "var(--bg-shell)",
  },
  welcomeMain: { flex: 1, display: "flex", overflow: "hidden" },
  sidebar: {
    width: 220,
    flexShrink: 0,
    background: "linear-gradient(180deg, var(--bg-sidebar), var(--bg-sidebar-elevated))",
    borderRight: "1px solid var(--border-dim)",
    display: "flex",
    flexDirection: "column",
    padding: "18px 14px 14px",
  },
  sidebarBrand: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "2px 6px 18px",
    marginBottom: 14,
    borderBottom: "1px solid var(--border-dim)",
  },
  sidebarBrandIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    background: "var(--brand-mark-gradient)",
    padding: 4,
    boxShadow: "0 10px 20px var(--brand-mark-glow)",
  },
  sidebarBrandBadge: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    width: "100%",
    height: "100%",
    borderRadius: 9,
    background: "var(--brand-mark-inner-bg)",
    color: "var(--brand-mark-fg)",
    fontSize: 15,
    fontWeight: 800,
    letterSpacing: 0.6,
    paddingBottom: 4,
  },
  sidebarBrandTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: "var(--text-primary)",
    lineHeight: 1.2,
  },
  sidebarBrandMeta: { marginTop: 3, fontSize: 12, color: "var(--text-muted)" },
  sidebarNav: { display: "flex", flexDirection: "column", gap: 6 },
  sidebarSectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-hint)",
    letterSpacing: 0.7,
    padding: "0 10px 6px",
    textTransform: "uppercase" as const,
  },
  sidebarItemMeta: {
    marginLeft: "auto",
    minWidth: 22,
    height: 22,
    padding: "0 7px",
    borderRadius: 999,
    background: "var(--badge-muted-bg)",
    color: "var(--text-muted)",
    fontSize: 11,
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  sidebarFooter: {
    marginTop: "auto",
    paddingTop: 10,
    borderTop: "1px solid var(--border-dim)",
    display: "flex",
    justifyContent: "flex-start",
  },
  sidebarFooterActions: { display: "flex", alignItems: "center", gap: 4 },
  sidebarIconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 4,
    borderRadius: 6,
    display: "flex",
    alignItems: "center",
    position: "relative",
    overflow: "visible",
    opacity: 0.5,
  },
  welcomePane: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "var(--bg-panel)",
  },
  searchRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "18px 22px 12px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-panel)",
    flexShrink: 0,
  },
  searchInput: {
    flex: 1,
    border: "none",
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 15,
    fontWeight: 500,
  },
  actionRow: { display: "flex", alignItems: "center", gap: 10, flexShrink: 0 },
  primaryActionBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    height: 38,
    padding: "0 16px",
    background: "var(--bg-card)",
    color: "var(--text-primary)",
    border: "1px solid var(--border-medium)",
    borderRadius: 10,
    fontSize: 13.5,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "var(--shadow-xs)",
  },
  projectSectionHeader: { padding: "14px 22px 6px", flexShrink: 0 },
  projectSectionTitle: { fontSize: 14, fontWeight: 700, color: "var(--text-primary)" },
  projectSectionCaption: { marginTop: 4, fontSize: 12, color: "var(--text-muted)" },
  projectList: { flex: 1, overflowY: "auto", padding: "4px 22px 18px" },
  railHiddenIcon: {
    marginLeft: "auto",
    flexShrink: 0,
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    padding: 32,
    textAlign: "center",
  },
  emptyOpenBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    padding: "10px 18px",
    background: "var(--bg-card)",
    color: "var(--text-secondary)",
    border: "1px solid var(--border-medium)",
    borderRadius: 12,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "var(--shadow-sm)",
  },
  projectBody: { flex: 1, display: "flex", overflow: "hidden" },
  // 非激活项目必须 display:none：visibility:hidden 仍留在 layout tree，会让 macOS
  // WKWebView 的 NSTextInputClient 在中文 IME 拖选时扫描隐藏项目的 RenderText。
  projectBodyVisible: {
    flex: 1,
    display: "flex",
    overflow: "hidden",
    position: "absolute" as const,
    inset: 0,
    pointerEvents: "auto" as const,
    zIndex: 1,
  },
  projectBodyHidden: {
    flex: 1,
    display: "none",
    overflow: "hidden",
    position: "absolute" as const,
    inset: 0,
    pointerEvents: "none" as const,
    zIndex: 0,
  },
  mainContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "var(--bg-panel)",
  },
  // 主舞台顶部的布局模式切换工具条
  mainStageModeBar: {
    height: 32,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    padding: "0 8px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-sidebar)",
  },
  mainStageModeBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 10px",
    borderRadius: 6,
    border: "1px solid var(--border-dim)",
    background: "var(--bg-card)",
    color: "var(--text-secondary)",
    fontSize: 12,
    cursor: "pointer",
  },
  projectMainStage: {
    flex: 1,
    display: "flex",
    flexDirection: "row" as const,
    overflow: "hidden",
    minWidth: 0,
    minHeight: 0,
    position: "relative" as const,
  },
  // fullscreen 模式：Nezha 原始覆盖式 —— 内容前景覆盖 PTY 背景
  mainStageFullscreen: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    position: "relative" as const,
    overflow: "hidden",
  },
  // PTY 背景层：absolute 铺满，打开文件时被内容前景覆盖
  mainStageFullscreenPty: {
    position: "absolute" as const,
    inset: 0,
    zIndex: 0,
    overflow: "hidden",
  },
  // 内容前景层：占满主舞台，盖在 PTY 之上
  mainStageFullscreenContent: {
    position: "relative" as const,
    zIndex: 1,
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
  },
  // 中央舞台左右并排：左=任务 PTY 终端，右=已打开文件/diff/新建任务
  // （flexGrow 由 ProjectPage 按 mainStageRatio 动态传入；此处仅保证可收缩）
  // 左列加 position:relative，使 RunningView 的 absolute inset:0 只铺满左列，
  // 不会覆盖并排的右列。
  mainStageLeft: {
    position: "relative" as const,
    minWidth: 0,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
  },
  mainStageRight: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
  },
  mainStageDivider: {
    width: 6,
    flexShrink: 0,
    cursor: "col-resize",
    background: "var(--border-dim)",
    position: "relative" as const,
    zIndex: 5,
  },
  mainStagePtyEmpty: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--text-muted)",
    fontSize: 12,
  },
  // 右列「已打开文件内容」空态：常驻容器，无文件时提示
  mainStageContentEmpty: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    color: "var(--text-muted)",
    fontSize: 13,
  },
  rightPanelWrap: { position: "relative" as const, display: "flex", flexShrink: 0 },
  rightPanelWrapCol: {
    position: "relative" as const,
    display: "flex",
    flexDirection: "column" as const,
    flexShrink: 0,
  },
  // 构建面板保持挂载但非激活时隐藏（替代卸载，保住构建会话状态）
  rpHiddenCol: { display: "none" as const },
  // 右侧边栏：悬浮态（absolute，脱离内容流，不挤占中央舞台宽度）
  // right: 44 避开最右的 RightToolbar 竖条；zIndex 盖在内容上方
  rightPanelFloat: {
    position: "absolute" as const,
    top: 0,
    right: 44,
    bottom: 0,
    zIndex: 20,
    display: "flex",
    flexDirection: "column" as const,
    boxShadow: "var(--shadow-md)",
    borderLeft: "1px solid var(--border-dim)",
    background: "var(--bg-panel)",
  },
  // 右侧边栏：固定态（flex 常驻列，从右缘向左占宽，挤窄中央舞台）
  rightPanelDock: {
    position: "relative" as const,
    display: "flex",
    flexDirection: "column" as const,
    flexShrink: 0,
  },
  // 右侧边栏整体包裹：横向 flex 兄弟。悬浮时零宽（面板 absolute 盖内容上），
  // 固定时占 rightPanelWidth（挤窄中央舞台）。
  rightSideWrap: {
    display: "flex",
    minWidth: 0,
    overflow: "hidden",
    position: "relative" as const,
    flexShrink: 0,
  },
  rightSideWrapFloat: { width: 0, flexShrink: 0 },
  rightSideWrapDock: { flexShrink: 0 },
  rightPanelResizeHandle: {
    position: "absolute" as const,
    left: 0,
    top: 0,
    bottom: 0,
    width: 5,
    cursor: "col-resize",
    zIndex: 10,
  },
  rpTabs: {
    display: "flex",
    gap: 2,
    padding: "4px 8px",
    borderBottom: "1px solid var(--border-dim)",
    flexShrink: 0,
  },
  rpTab: {
    flex: 1,
    padding: "6px 4px",
    textAlign: "center" as const,
    fontSize: 11.5,
    color: "var(--text-muted)",
    borderRadius: 7,
    border: "1px solid transparent",
    background: "transparent",
    cursor: "pointer",
  },
  rpTabActive: {
    background: "var(--accent-subtle)",
    color: "var(--accent)",
    fontWeight: 700,
  },
  rpContent: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    overflow: "hidden",
  },
  placeholderView: { flex: 1, display: "flex", alignItems: "center", justifyContent: "center" },
} satisfies Record<string, React.CSSProperties>;
