import type React from "react";

/** 方案待办的「前置依赖」UI：列表行等待角标 + 详情 Checklist + 确认页依赖编辑。 */
export const planDeps = {
  // ── 列表行角标（TaskListItem） ───────────────────────────────────────────
  taskWaitingBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    marginLeft: 6,
    padding: "1px 5px",
    borderRadius: 4,
    fontSize: 10,
    fontWeight: 600,
    // 「前置待完成」与「排队等槽位」用不同色调区分，四个主题下均取语义变量。
    background: "var(--bg-hover)",
    color: "var(--text-muted)",
    border: "1px solid var(--border-dim)",
    whiteSpace: "nowrap",
  } satisfies React.CSSProperties,
  taskWaitingBadgeBlocked: {
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    marginLeft: 6,
    padding: "1px 5px",
    borderRadius: 4,
    fontSize: 10,
    fontWeight: 600,
    background: "var(--danger-bg, var(--bg-hover))",
    color: "var(--danger)",
    border: "1px solid var(--danger-border, var(--danger))",
    whiteSpace: "nowrap",
  } satisfies React.CSSProperties,

  // ── 详情 Checklist ──────────────────────────────────────────────────────
  depsSection: {
    marginTop: 4,
  } satisfies React.CSSProperties,
  depsHint: {
    fontSize: 11,
    color: "var(--text-hint)",
    lineHeight: 1.6,
    marginTop: 2,
  } satisfies React.CSSProperties,
  depsList: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    marginTop: 8,
  } satisfies React.CSSProperties,
  depsEntry: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 8px",
    borderRadius: 6,
    background: "var(--bg-hover)",
    border: "1px solid var(--border-dim)",
  } satisfies React.CSSProperties,
  depsEntryDone: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 8px",
    borderRadius: 6,
    background: "transparent",
    border: "1px solid var(--border-dim)",
    opacity: 0.85,
  } satisfies React.CSSProperties,
  depsEntryAbnormal: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 8px",
    borderRadius: 6,
    background: "var(--bg-hover)",
    border: "1px solid var(--danger)",
  } satisfies React.CSSProperties,
  depsEntryIcon: {
    display: "inline-flex",
    flexShrink: 0,
  } satisfies React.CSSProperties,
  depsEntryBody: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 6,
  } satisfies React.CSSProperties,
  depsEntrySerial: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--accent)",
    whiteSpace: "nowrap",
  } satisfies React.CSSProperties,
  depsEntrySubject: {
    fontSize: 12,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies React.CSSProperties,
  depsEntryStatus: {
    flexShrink: 0,
    fontSize: 11,
    color: "var(--text-muted)",
    whiteSpace: "nowrap",
  } satisfies React.CSSProperties,
  depsEntryStatusAbnormal: {
    flexShrink: 0,
    fontSize: 11,
    color: "var(--danger)",
    fontWeight: 600,
    whiteSpace: "nowrap",
  } satisfies React.CSSProperties,
  depsEntryJump: {
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 2,
    background: "transparent",
    border: "none",
    borderRadius: 4,
    color: "var(--text-hint)",
    cursor: "pointer",
  } satisfies React.CSSProperties,
  depsActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginTop: 10,
    flexWrap: "wrap",
  } satisfies React.CSSProperties,
  depsOverrideNote: {
    fontSize: 11,
    color: "var(--danger)",
    marginTop: 8,
    lineHeight: 1.6,
  } satisfies React.CSSProperties,

  // ── 确认页依赖编辑（GeneratePlanTodosDialog） ──────────────────────────
  depsEditBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    paddingLeft: 34,
    paddingBottom: 4,
  } satisfies React.CSSProperties,
  depsEditRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  } satisfies React.CSSProperties,
  depsEditLabel: {
    fontSize: 11,
    color: "var(--text-muted)",
  } satisfies React.CSSProperties,
  depsChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    padding: "1px 6px",
    borderRadius: 4,
    fontSize: 11,
    background: "var(--bg-hover)",
    border: "1px solid var(--border-dim)",
    color: "var(--text-primary)",
  } satisfies React.CSSProperties,
  depsChipRemove: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    marginLeft: 2,
    background: "transparent",
    border: "none",
    color: "var(--text-hint)",
    cursor: "pointer",
  } satisfies React.CSSProperties,
  depsEditNone: {
    fontSize: 11,
    color: "var(--text-hint)",
  } satisfies React.CSSProperties,
  depsChipAdd: {
    display: "inline-flex",
    alignItems: "center",
    gap: 2,
    color: "var(--text-hint)",
  } satisfies React.CSSProperties,
  depsWarningRow: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    padding: "6px 8px",
    borderRadius: 6,
    background: "var(--bg-hover)",
    border: "1px solid var(--border-dim)",
    fontSize: 11,
    color: "var(--text-muted)",
    lineHeight: 1.6,
  } satisfies React.CSSProperties,
} satisfies Record<string, React.CSSProperties>;
