import type React from "react";

/**
 * 行级 Review 评论的样式（FileViewer 内）。
 * 命名统一 rc 前缀，避免与既有模块 key 冲突。
 */
export const reviewComments = {
  // ── 选中浮出气泡（＋评论） ─────────────────────────────
  rcBubble: {
    position: "fixed" as const,
    zIndex: 1100,
    width: 24,
    height: 24,
    padding: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "var(--primary-action-bg)",
    color: "var(--primary-action-fg)",
    border: "none",
    borderRadius: "50%",
    boxShadow: "var(--shadow-popover)",
    cursor: "pointer",
    fontSize: 15,
    lineHeight: 1,
    transform: "translate(-50%, -50%)",
  },

  // ── 右键菜单（选区 → 添加评论） ────────────────────────
  rcCtxMenu: {
    position: "fixed" as const,
    zIndex: 1200,
    minWidth: 148,
    padding: "3px 0",
    background: "var(--bg-sidebar)",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
    boxShadow: "var(--shadow-popover)",
    fontSize: 12.5,
  },
  rcCtxMenuItem: {
    display: "block",
    width: "calc(100% - 8px)",
    height: 26,
    margin: "2px 4px",
    padding: "0 10px",
    border: "none",
    borderRadius: 3,
    background: "transparent",
    color: "var(--text-primary)",
    textAlign: "left" as const,
    fontSize: 12.5,
    fontFamily: "var(--font-ui)",
    lineHeight: "26px",
    cursor: "pointer",
  },

  // ── 评论输入卡片（Composer） ───────────────────────────
  rcComposer: {
    position: "fixed" as const,
    zIndex: 1300,
    width: 340,
    maxWidth: "calc(100vw - 32px)",
    display: "flex",
    flexDirection: "column" as const,
    gap: 6,
    padding: 10,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 10,
    boxShadow: "var(--shadow-popover)",
    boxSizing: "border-box" as const,
  },
  rcComposerLoc: {
    fontSize: 11.5,
    fontWeight: 600,
    color: "var(--accent)",
    fontFamily: "var(--font-mono)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  rcComposerSnippet: {
    maxHeight: 120,
    overflowY: "auto" as const,
    margin: 0,
    padding: "6px 8px",
    background: "var(--bg-subtle)",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
    fontFamily: "var(--font-mono)",
    fontSize: 11,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap" as const,
    wordBreak: "break-all" as const,
  },
  rcComposerTextarea: {
    display: "block",
    width: "100%",
    minHeight: 56,
    maxHeight: 160,
    padding: "6px 8px",
    boxSizing: "border-box" as const,
    background: "var(--bg-input, var(--bg-sidebar))",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
    outline: "none",
    resize: "vertical" as const,
    color: "var(--text-primary)",
    fontFamily: "var(--font-ui)",
    fontSize: 12.5,
    lineHeight: 1.5,
  },
  rcComposerActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
  },
  rcComposerBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    minHeight: 26,
    padding: "3px 12px",
    border: "1px solid var(--border-medium)",
    borderRadius: 6,
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 500,
    fontFamily: "var(--font-ui)",
    cursor: "pointer",
  },
  rcComposerBtnPrimary: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    minHeight: 26,
    padding: "3px 12px",
    border: "1px solid transparent",
    borderRadius: 6,
    background: "var(--primary-action-bg)",
    color: "var(--primary-action-fg)",
    fontSize: 12,
    fontWeight: 600,
    fontFamily: "var(--font-ui)",
    cursor: "pointer",
  },

  // ── 底部评论抽屉 ───────────────────────────────────────
  rcDrawerBar: {
    flexShrink: 0,
    height: 26,
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "0 10px",
    borderTop: "1px solid var(--border-dim)",
    background: "var(--bg-subtle)",
    cursor: "pointer",
    userSelect: "none" as const,
  },
  rcDrawerBarTitle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
  },
  rcDrawerBarCount: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 16,
    height: 16,
    padding: "0 5px",
    borderRadius: 999,
    background: "var(--accent)",
    color: "var(--fg-on-accent)",
    fontSize: 10,
    fontWeight: 700,
    lineHeight: 1,
  },
  rcDrawerBarChevron: {
    marginLeft: "auto",
    color: "var(--text-hint)",
  },
  rcDrawer: {
    flexShrink: 0,
    maxHeight: 240,
    display: "flex",
    flexDirection: "column" as const,
    borderTop: "1px solid var(--border-dim)",
    background: "var(--bg-subtle)",
  },
  rcDrawerHeader: {
    flexShrink: 0,
    height: 34,
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "0 10px",
  },
  rcDrawerHeaderTitle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11.5,
    fontWeight: 700,
    color: "var(--text-hint)",
    letterSpacing: 0.4,
    textTransform: "uppercase" as const,
  },
  rcDrawerSendBtn: {
    marginLeft: "auto",
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    minHeight: 24,
    padding: "2px 10px",
    border: "none",
    borderRadius: 6,
    background: "var(--primary-action-bg)",
    color: "var(--primary-action-fg)",
    fontSize: 11.5,
    fontWeight: 600,
    fontFamily: "var(--font-ui)",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  rcDrawerList: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto" as const,
    padding: "0 6px 6px",
  },
  rcDrawerItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 7,
    padding: "6px 8px",
    border: "1px solid var(--border-dim)",
    borderRadius: 7,
    background: "var(--bg-card)",
    marginTop: 5,
    cursor: "pointer",
  },
  rcDrawerItemCheckbox: {
    flexShrink: 0,
    marginTop: 2,
    accentColor: "var(--accent)",
    cursor: "pointer",
  },
  rcDrawerItemMain: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column" as const,
    gap: 2,
  },
  rcDrawerItemLoc: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--accent)",
    fontFamily: "var(--font-mono)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  rcDrawerItemSnippet: {
    fontSize: 11,
    color: "var(--text-hint)",
    fontFamily: "var(--font-mono)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  rcDrawerItemText: {
    fontSize: 12,
    color: "var(--text-primary)",
    lineHeight: 1.4,
    overflow: "hidden",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical" as const,
    wordBreak: "break-word" as const,
  },
  rcDrawerItemMeta: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    flexShrink: 0,
    marginTop: 2,
  },
  rcDrawerChip: {
    display: "inline-flex",
    alignItems: "center",
    fontSize: 10,
    fontWeight: 600,
    padding: "1px 6px",
    borderRadius: 999,
    lineHeight: "14px",
    whiteSpace: "nowrap" as const,
  },
  rcDrawerChipOpen: {
    background: "color-mix(in srgb, var(--accent) 14%, transparent)",
    color: "var(--accent)",
  },
  rcDrawerChipResolved: {
    background: "var(--bg-hover)",
    color: "var(--text-hint)",
  },
  rcDrawerChipSent: {
    background: "var(--bg-hover)",
    color: "var(--text-hint)",
  },
  rcDrawerItemActions: {
    display: "flex",
    alignItems: "center",
    gap: 1,
    flexShrink: 0,
  },
  rcDrawerIconBtn: {
    width: 22,
    height: 22,
    padding: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    borderRadius: 4,
    background: "transparent",
    color: "var(--text-hint)",
    cursor: "pointer",
  },
  rcDrawerIconBtnSend: {
    width: 22,
    height: 22,
    padding: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    borderRadius: 4,
    background: "transparent",
    color: "var(--accent)",
    cursor: "pointer",
  },
  rcDrawerEditInput: {
    flex: 1,
    minWidth: 0,
    padding: "3px 6px",
    background: "var(--bg-input, var(--bg-sidebar))",
    border: "1px solid var(--accent)",
    borderRadius: 5,
    outline: "none",
    color: "var(--text-primary)",
    fontFamily: "var(--font-ui)",
    fontSize: 12,
  },
  rcDrawerEmpty: {
    padding: "14px 10px",
    fontSize: 12,
    color: "var(--text-hint)",
    textAlign: "center" as const,
  },

  // ── 发送对话框 ─────────────────────────────────────────
  rcSendBackdrop: {
    position: "fixed" as const,
    inset: 0,
    zIndex: 1600,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "color-mix(in srgb, var(--bg-root) 38%, transparent)",
  },
  rcSendDialog: {
    width: "min(460px, calc(100vw - 56px))",
    display: "flex",
    flexDirection: "column" as const,
    gap: 10,
    padding: 16,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 10,
    boxShadow: "var(--shadow-popover)",
    boxSizing: "border-box" as const,
  },
  rcSendTitle: {
    fontSize: 13.5,
    fontWeight: 700,
    color: "var(--text-primary)",
  },
  rcSendField: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 4,
  },
  rcSendFieldLabel: {
    fontSize: 11.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
  },
  rcSendTargetTrigger: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    minHeight: 30,
    padding: "4px 10px",
    background: "var(--bg-input, var(--bg-sidebar))",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
    color: "var(--text-primary)",
    fontSize: 12.5,
    fontFamily: "var(--font-ui)",
    cursor: "pointer",
    outline: "none",
  },
  rcSendTargetContent: {
    zIndex: 1700,
    background: "var(--bg-sidebar)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    boxShadow: "var(--shadow-md)",
    padding: 4,
    minWidth: 220,
  },
  rcSendTargetItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 28,
    padding: "0 9px",
    borderRadius: 5,
    cursor: "pointer",
    color: "var(--text-primary)",
    fontSize: 12.5,
    outline: "none",
  },
  rcSendTargetItemSelected: {
    background: "var(--bg-selected)",
  },
  rcSendCommentList: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 3,
    maxHeight: 120,
    overflowY: "auto" as const,
    padding: "6px 8px",
    background: "var(--bg-subtle)",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
  },
  rcSendCommentLoc: {
    fontSize: 11.5,
    color: "var(--text-secondary)",
    fontFamily: "var(--font-mono)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  rcSendHint: {
    fontSize: 11.5,
    color: "var(--text-hint)",
    lineHeight: 1.5,
  },
  rcSendHintWarning: {
    fontSize: 11.5,
    color: "var(--warning)",
    lineHeight: 1.5,
  },
  rcSendActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
    marginTop: 2,
  },
  rcSendBtnPrimary: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    minHeight: 28,
    padding: "4px 14px",
    border: "1px solid transparent",
    borderRadius: 6,
    background: "var(--primary-action-bg)",
    color: "var(--primary-action-fg)",
    fontSize: 12.5,
    fontWeight: 600,
    fontFamily: "var(--font-ui)",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  rcSendBtnSecondary: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    minHeight: 28,
    padding: "4px 14px",
    border: "1px solid var(--border-medium)",
    borderRadius: 6,
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 12.5,
    fontWeight: 500,
    fontFamily: "var(--font-ui)",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
} satisfies Record<string, React.CSSProperties>;
