import type React from "react";

export const update = {
  updateBanner: {
    position: "absolute" as const,
    top: 0,
    left: 0,
    right: 0,
    zIndex: 900,
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "8px 16px",
    background: "color-mix(in srgb, var(--accent) 12%, var(--bg-card))",
    borderBottom: "1px solid var(--border-medium)",
    backdropFilter: "blur(6px)",
  },
  updateBannerText: {
    flex: 1,
    minWidth: 0,
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-primary)",
    whiteSpace: "nowrap" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  updateBannerBtn: {
    flexShrink: 0,
    padding: "4px 12px",
    borderRadius: 6,
    border: "1px solid var(--accent)",
    color: "var(--accent)",
    background: "transparent",
    fontSize: 12,
    cursor: "pointer",
    outline: "none",
  },
  updateBannerClose: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 20,
    height: 20,
    borderRadius: 5,
    border: "none",
    background: "transparent",
    color: "var(--text-hint)",
    cursor: "pointer",
  },
  updateDialogCard: {
    width: "min(560px, calc(100vw - 48px))",
    maxHeight: "calc(100vh - 96px)",
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 14,
    boxShadow: "var(--shadow-popover)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  updateDialogHeader: {
    padding: "14px 16px",
    borderBottom: "1px solid var(--border-dim)",
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  updateDialogTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: 700,
    color: "var(--text-primary)",
  },
  updateDialogContent: {
    padding: "16px",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  updateVersionRow: {
    display: "flex",
    alignItems: "baseline",
    gap: 10,
    flexWrap: "wrap" as const,
  },
  updateNewVersion: {
    fontSize: 18,
    fontWeight: 800,
    color: "var(--accent)",
  },
  updateCurrentVersion: {
    fontSize: 12.5,
    color: "var(--text-muted)",
  },
  updateMetaText: {
    fontSize: 11,
    color: "var(--text-hint)",
  },
  updateBody: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.6,
    whiteSpace: "pre-line" as const,
    fontFamily: "var(--font-ui)",
    margin: 0,
    background: "var(--bg-subtle)",
    border: "1px solid var(--border-dim)",
    borderRadius: 10,
    padding: "12px 14px",
    maxHeight: 220,
    overflowY: "auto" as const,
  },
  updateHint: {
    fontSize: 13,
    color: "var(--text-muted)",
  },
  updateError: {
    fontSize: 13,
    color: "var(--danger)",
    lineHeight: 1.5,
  },
  updateUpToDateWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  updateUpToDateTitle: {
    fontSize: 15,
    fontWeight: 700,
    color: "var(--accent)",
  },
  updateMuted: {
    fontSize: 12.5,
    color: "var(--text-muted)",
  },
  updateFooter: {
    padding: "0 16px 16px",
  },
  updateBodyLabel: {
    fontSize: 11,
    color: "var(--text-hint)",
    marginBottom: 6,
  },
  updateProgressTrack: {
    height: 8,
    borderRadius: 5,
    background: "var(--bg-hover)",
    overflow: "hidden" as const,
  },
  updateProgressFill: {
    height: "100%",
    borderRadius: 5,
    background: "var(--accent)",
    transition: "width 0.2s ease",
  },
  updateProgressLabel: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    textAlign: "right" as const,
  },
  updateWarning: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "10px 12px",
    borderRadius: 10,
    background: "color-mix(in srgb, var(--color-warning) 12%, transparent)",
    color: "var(--text-secondary)",
    fontSize: 12,
    lineHeight: 1.5,
  },
  updateButtons: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 10,
  },
  updatePrimaryBtn: {
    padding: "6px 16px",
    borderRadius: 7,
    border: "none",
    background: "var(--accent)",
    color: "var(--fg-on-accent)",
    fontSize: 12.5,
    fontWeight: 600,
    cursor: "pointer",
    outline: "none",
  },
  updateSecondaryBtn: {
    padding: "6px 16px",
    borderRadius: 7,
    border: "1px solid var(--border-medium)",
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 12.5,
    cursor: "pointer",
    outline: "none",
  },
  updatePrimaryDisabled: {
    opacity: 0.5,
    cursor: "default" as const,
  },
} satisfies Record<string, React.CSSProperties>;
