import type React from "react";

export const weeklyReport = {
  pane: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    overflowY: "auto" as const,
    background: "var(--bg-panel)",
    padding: "30px 34px 40px",
  },
  inner: {
    width: "100%",
    maxWidth: 1060,
    margin: "0 auto",
  },
  header: {
    display: "flex",
    alignItems: "flex-end" as const,
    justifyContent: "space-between" as const,
    gap: 20,
    marginBottom: 26,
  },
  headTitle: {
    fontSize: 25,
    fontWeight: 700,
    color: "var(--text-primary)",
    letterSpacing: -0.2,
  },
  headSub: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    marginTop: 5,
  },
  actions: {
    display: "flex",
    alignItems: "center" as const,
    gap: 10,
  },
  seg: {
    display: "inline-flex",
    background: "var(--bg-sidebar)",
    border: "1px solid var(--border-dim)",
    borderRadius: 10,
    padding: 3,
    gap: 2,
  },
  segBtn: {
    border: 0,
    background: "transparent",
    padding: "7px 16px",
    borderRadius: 8,
    fontSize: 12.5,
    color: "var(--text-muted)",
    cursor: "pointer",
  },
  segActive: {
    background: "var(--control-selected-bg)",
    color: "var(--control-selected-fg)",
    fontWeight: 600,
  },
  btn: {
    border: "1px solid var(--border-medium)",
    background: "var(--bg-panel)",
    color: "var(--text-secondary)",
    padding: "8px 15px",
    borderRadius: 9,
    fontSize: 12.5,
    cursor: "pointer",
  },
  btnPrimary: {
    background: "var(--accent-strong)",
    borderColor: "transparent",
    color: "var(--fg-on-accent)",
    fontWeight: 600,
  },
  btnDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  stats: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: 14,
  },
  stat: {
    position: "relative",
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    borderRadius: 14,
    padding: "16px 20px 16px 22px",
    overflow: "hidden" as const,
  },
  statAccent: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    background: "linear-gradient(var(--accent), #8b5eef)",
  },
  statKey: {
    fontSize: 11,
    color: "var(--text-muted)",
    letterSpacing: 0.08,
    textTransform: "uppercase" as const,
  },
  statValue: {
    fontSize: 30,
    fontWeight: 700,
    color: "var(--text-primary)",
    marginTop: 7,
    fontVariantNumeric: "tabular-nums" as const,
    lineHeight: 1,
  },
  statSub: {
    fontSize: 12,
    color: "var(--text-hint)",
    marginTop: 8,
  },
  summaryCard: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    borderRadius: 14,
    padding: "18px 22px 20px",
    marginBottom: 20,
  },
  summaryHead: {
    display: "flex",
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    gap: 16,
    marginBottom: 12,
  },
  summaryTitle: {
    fontSize: 13,
    fontWeight: 650,
    color: "var(--text-secondary)",
  },
  sectionLabel: {
    display: "flex",
    alignItems: "center" as const,
    gap: 9,
    color: "var(--text-secondary)",
    fontSize: 11.5,
    fontWeight: 650,
    letterSpacing: 0.06,
    textTransform: "uppercase" as const,
    margin: "26px 0 14px",
  },
  sectionDot: {
    width: 4,
    height: 15,
    borderRadius: 4,
    background: "linear-gradient(var(--accent), #8b5eef)",
  },
  group: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    borderRadius: 14,
    marginBottom: 12,
    overflow: "hidden" as const,
  },
  groupHead: {
    display: "flex",
    alignItems: "center" as const,
    gap: 12,
    padding: "13px 16px",
  },
  avatar: {
    width: 30,
    height: 30,
    borderRadius: 10,
    background: "var(--accent-subtle)",
    color: "var(--accent-strong)",
    display: "grid",
    placeItems: "center" as const,
    fontSize: 13,
    fontWeight: 700,
    fontFamily: "var(--font-mono)",
  },
  groupName: {
    fontWeight: 650,
    color: "var(--text-primary)",
    fontSize: 14,
  },
  groupSub: {
    fontSize: 12,
    color: "var(--text-muted)",
    marginLeft: 2,
  },
  badge: {
    marginLeft: "auto",
    background: "var(--accent-subtle)",
    color: "var(--accent-strong)",
    fontSize: 12,
    fontWeight: 650,
    padding: "3px 12px",
    borderRadius: 20,
  },
  rows: {
    padding: "2px 6px 8px",
  },
  row: {
    display: "flex",
    alignItems: "center" as const,
    gap: 12,
    padding: "10px 12px",
    borderRadius: 9,
  },
  datePill: {
    background: "var(--bg-subtle)",
    color: "var(--text-secondary)",
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    fontWeight: 600,
    fontVariantNumeric: "tabular-nums" as const,
    padding: "3px 9px",
    borderRadius: 7,
    minWidth: 56,
    textAlign: "center",
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    flex: "none",
    background: "var(--accent)",
  },
  rowTitle: {
    flex: 1,
    minWidth: 0,
    color: "var(--text-primary)",
    fontSize: 13.5,
    whiteSpace: "nowrap" as const,
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
  },
  chip: {
    flex: "none",
    background: "var(--accent-subtle)",
    color: "var(--accent-strong)",
    fontSize: 12,
    fontWeight: 600,
    padding: "3px 10px",
    borderRadius: 20,
  },
  gitGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: 12,
  },
  gitCard: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    borderRadius: 14,
    padding: "15px 18px",
  },
  gitName: {
    color: "var(--text-secondary)",
    fontSize: 13,
    fontWeight: 600,
    whiteSpace: "nowrap" as const,
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
  },
  gitNum: {
    fontSize: 26,
    fontWeight: 700,
    color: "var(--text-primary)",
    marginTop: 6,
    fontVariantNumeric: "tabular-nums" as const,
    lineHeight: 1,
  },
  hint: {
    color: "var(--text-muted)",
    fontSize: 13,
    padding: "28px 0",
  },
} satisfies Record<string, React.CSSProperties>;
