import type React from "react";

export const weeklyReport = {
  pane: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    overflowY: "auto" as const,
    background: "var(--bg-panel)",
    padding: "28px 30px 36px",
  },
  header: {
    display: "flex",
    alignItems: "flex-end" as const,
    justifyContent: "space-between" as const,
    gap: 20,
    marginBottom: 20,
  },
  headTitle: {
    fontSize: 24,
    fontWeight: 700,
    color: "var(--text-primary)",
    letterSpacing: 0.2,
  },
  headSub: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    marginTop: 3,
  },
  actions: {
    display: "flex",
    alignItems: "center" as const,
    gap: 10,
  },
  seg: {
    display: "inline-flex",
    background: "var(--bg-sidebar)",
    border: "1px solid var(--border-dim)",
    borderRadius: 9,
    padding: 3,
    gap: 2,
  },
  segBtn: {
    border: 0,
    background: "transparent",
    padding: "6px 16px",
    borderRadius: 7,
    fontSize: 12.5,
    color: "var(--text-muted)",
    cursor: "pointer",
  },
  segActive: {
    background: "var(--control-selected-bg)",
    color: "var(--control-selected-fg)",
    fontWeight: 600,
  },
  btn: {
    border: "1px solid var(--border-medium)",
    background: "var(--bg-panel)",
    color: "var(--text-secondary)",
    padding: "8px 14px",
    borderRadius: 8,
    fontSize: 12.5,
    cursor: "pointer",
  },
  btnPrimary: {
    background: "var(--accent-strong)",
    borderColor: "transparent",
    color: "var(--fg-on-accent)",
    fontWeight: 600,
  },
  btnDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  stats: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: 14,
    marginBottom: 24,
  },
  stat: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    borderRadius: 12,
    padding: "14px 18px",
  },
  statKey: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    letterSpacing: 0.3,
  },
  statValue: {
    fontSize: 28,
    fontWeight: 700,
    color: "var(--text-primary)",
    marginTop: 5,
    fontVariantNumeric: "tabular-nums" as const,
  },
  statSub: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    marginTop: 3,
  },
  sectionLabel: {
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
    color: "var(--text-secondary)",
    fontSize: 13,
    fontWeight: 600,
    margin: "24px 0 12px",
  },
  sectionDot: {
    width: 4,
    height: 16,
    borderRadius: 4,
    background: "linear-gradient(var(--accent), #8b5eef)",
  },
  group: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    borderRadius: 12,
    marginBottom: 14,
    overflow: "hidden" as const,
  },
  groupHead: {
    display: "flex",
    alignItems: "center" as const,
    gap: 12,
    padding: "12px 16px",
    borderBottom: "1px solid var(--border-dim)",
  },
  avatar: {
    width: 28,
    height: 28,
    borderRadius: 8,
    background: "var(--accent-subtle)",
    color: "var(--accent-strong)",
    display: "grid",
    placeItems: "center" as const,
    fontSize: 13,
    fontWeight: 700,
    fontFamily: "var(--font-mono)",
  },
  groupName: {
    fontWeight: 600,
    color: "var(--text-primary)",
  },
  groupSub: {
    fontSize: 12,
    color: "var(--text-muted)",
  },
  badge: {
    marginLeft: "auto",
    background: "var(--accent-subtle)",
    color: "var(--accent-strong)",
    fontSize: 12,
    fontWeight: 600,
    padding: "2px 10px",
    borderRadius: 20,
  },
  icon: {
    color: "var(--text-hint)",
  },
  rows: {
    padding: "6px 6px",
  },
  row: {
    display: "flex",
    alignItems: "flex-start" as const,
    gap: 12,
    padding: "9px 12px",
    borderRadius: 9,
  },
  date: {
    color: "var(--text-muted)",
    fontSize: 12.5,
    minWidth: 46,
    fontVariantNumeric: "tabular-nums" as const,
    paddingTop: 2,
  },
  dot: {
    width: 12,
    height: 12,
    borderRadius: "50%",
    flex: "none",
    marginTop: 5,
    background: "var(--accent)",
  },
  rowMain: {
    flex: 1,
    minWidth: 0,
  },
  rowTitle: {
    color: "var(--text-primary)",
    whiteSpace: "nowrap" as const,
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
  },
  rowMeta: {
    display: "flex",
    gap: 8,
    fontSize: 12,
    color: "var(--text-hint)",
    marginTop: 3,
  },
  chip: {
    background: "var(--accent-subtle)",
    color: "var(--accent-strong)",
    padding: "0 7px",
    borderRadius: 5,
  },
  gitGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: 12,
  },
  gitCard: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    borderRadius: 12,
    padding: "14px 16px",
  },
  gitName: {
    color: "var(--text-secondary)",
    fontSize: 13,
    fontWeight: 600,
  },
  gitNum: {
    fontSize: 24,
    fontWeight: 700,
    color: "var(--text-primary)",
    marginTop: 4,
  },
  hint: {
    color: "var(--text-muted)",
    fontSize: 13,
    padding: "24px 0",
  },
} satisfies Record<string, React.CSSProperties>;
