import type React from "react";

const yunxiaoIconBtn = {
  width: 28,
  height: 28,
  display: "flex",
  alignItems: "center" as const,
  justifyContent: "center" as const,
  borderRadius: 7,
  border: "1px solid var(--border-dim)",
  background: "transparent",
  color: "var(--text-muted)",
  cursor: "pointer",
  transition: "background 0.12s, color 0.12s, border-color 0.12s",
  flexShrink: 0,
};

const yunxiaoTabBase = {
  padding: "5px 12px",
  borderRadius: 7,
  border: "1px solid transparent",
  background: "transparent",
  color: "var(--text-muted)",
  fontSize: 12,
  fontWeight: 600,
  cursor: "pointer",
  transition: "background 0.12s, color 0.12s, border-color 0.12s",
};

const yunxiaoPrimaryBtnBase = {
  display: "inline-flex",
  alignItems: "center" as const,
  justifyContent: "center" as const,
  gap: 6,
  height: 32,
  padding: "0 14px",
  borderRadius: 8,
  border: "1px solid var(--border-medium)",
  background: "var(--bg-card)",
  color: "var(--text-primary)",
  fontSize: 12.5,
  fontWeight: 600,
  cursor: "pointer",
  transition: "background 0.12s, border-color 0.12s, opacity 0.12s",
};

export const yunxiao = {
  yunxiaoPane: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
    background: "var(--bg-panel)",
  },
  yunxiaoHeader: {
    display: "flex",
    alignItems: "center" as const,
    gap: 10,
    padding: "14px 18px 10px",
    borderBottom: "1px solid var(--border-dim)",
    flexShrink: 0,
  },
  yunxiaoBackBtn: {
    ...yunxiaoIconBtn,
  },
  yunxiaoBackBtnHover: {
    ...yunxiaoIconBtn,
    background: "var(--bg-hover)",
    color: "var(--text-primary)",
    borderColor: "var(--border-medium)",
  },
  yunxiaoHeaderTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: "var(--text-primary)",
  },
  yunxiaoHeaderMeta: {
    marginTop: 2,
    fontSize: 11.5,
    color: "var(--text-muted)",
  },
  yunxiaoHeaderActions: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
    flexShrink: 0,
  },
  yunxiaoToolbarBtn: {
    ...yunxiaoIconBtn,
    width: 30,
    height: 30,
  },
  yunxiaoToolbarBtnHover: {
    ...yunxiaoIconBtn,
    width: 30,
    height: 30,
    background: "var(--bg-hover)",
    color: "var(--text-primary)",
    borderColor: "var(--border-medium)",
  },
  yunxiaoToolbar: {
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
    padding: "10px 18px",
    borderBottom: "1px solid var(--border-dim)",
    flexShrink: 0,
    flexWrap: "wrap" as const,
  },
  yunxiaoTabs: {
    display: "flex",
    alignItems: "center" as const,
    gap: 4,
  },
  yunxiaoProjectPicker: {
    display: "flex",
    alignItems: "center" as const,
    gap: 6,
  },
  yunxiaoProjectSelect: {
    width: 200,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
    padding: "6px 24px 6px 10px",
    background: "var(--bg-elevated, var(--bg-card))",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    color: "var(--text-primary)",
    fontSize: 12.5,
    fontFamily: "var(--font-ui)",
    cursor: "pointer",
    textAlign: "left" as const,
    outline: "none",
  },
  yunxiaoTab: {
    ...yunxiaoTabBase,
  },
  yunxiaoTabActive: {
    ...yunxiaoTabBase,
    background: "var(--bg-elevated, var(--bg-card))",
    borderColor: "var(--border-medium)",
    color: "var(--text-primary)",
  },
  yunxiaoFilterBtn: {
    display: "inline-flex",
    alignItems: "center" as const,
    gap: 5,
    padding: "5px 12px",
    borderRadius: 7,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-elevated, var(--bg-card))",
    color: "var(--text-primary)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    transition: "background 0.12s, color 0.12s, border-color 0.12s",
  },
  yunxiaoFilterBtnActive: {
    display: "inline-flex",
    alignItems: "center" as const,
    gap: 5,
    padding: "5px 12px",
    borderRadius: 7,
    border: "1px solid var(--accent)",
    background: "var(--bg-elevated, var(--bg-card))",
    color: "var(--text-primary)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    transition: "background 0.12s, color 0.12s, border-color 0.12s",
  },
  yunxiaoFilterBtnDisabled: {
    display: "inline-flex",
    alignItems: "center" as const,
    gap: 5,
    padding: "5px 12px",
    borderRadius: 7,
    border: "1px solid var(--border-dim)",
    background: "transparent",
    color: "var(--text-muted)",
    fontSize: 12,
    fontWeight: 600,
    opacity: 0.5,
    cursor: "default",
    pointerEvents: "none" as const,
  },
  yunxiaoFilterPopover: {
    width: 240,
    maxHeight: 280,
    overflowY: "auto" as const,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 10,
    padding: 8,
    boxShadow: "var(--shadow-md)",
    zIndex: 9999,
  },
  yunxiaoFilterPopoverHeader: {
    display: "flex",
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    padding: "4px 6px 8px",
    fontSize: 11.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
  },
  yunxiaoFilterClear: {
    background: "none",
    border: "none",
    padding: 0,
    color: "var(--accent)",
    fontSize: 11,
    fontWeight: 600,
    cursor: "pointer",
  },
  yunxiaoFilterRetry: {
    marginTop: 6,
    padding: "5px 14px",
    borderRadius: 7,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-elevated, var(--bg-card))",
    color: "var(--accent)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    transition: "background 0.12s, border-color 0.12s",
  },
  yunxiaoFilterOptions: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 2,
  },
  yunxiaoFilterOption: {
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
    padding: "6px 8px",
    borderRadius: 7,
    fontSize: 12.5,
    color: "var(--text-primary)",
    cursor: "pointer",
    transition: "background 0.12s",
  },
  yunxiaoFilterOptionChecked: {
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
    padding: "6px 8px",
    borderRadius: 7,
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-primary)",
    cursor: "pointer",
    background: "var(--bg-hover)",
    transition: "background 0.12s",
  },
  yunxiaoFilterOptionLabel: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
    whiteSpace: "nowrap" as const,
  },
  yunxiaoFilterCheckbox: {
    width: 14,
    height: 14,
    accentColor: "var(--accent)",
    cursor: "pointer",
    flexShrink: 0,
  },
  yunxiaoFilterEmpty: {
    padding: "14px 8px",
    fontSize: 12,
    color: "var(--text-hint)",
    textAlign: "center" as const,
  },
  yunxiaoFilterLoading: {
    display: "flex",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    padding: "14px 8px",
    color: "var(--text-hint)",
  },
  yunxiaoSearchBox: {
    flex: 1,
    minWidth: 180,
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
    background: "var(--bg-elevated, var(--bg-card))",
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    padding: "6px 10px",
  },
  yunxiaoSearchInput: {
    flex: 1,
    border: "none",
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 12.5,
  },
  yunxiaoCount: {
    fontSize: 11,
    color: "var(--text-hint)",
    flexShrink: 0,
    fontVariantNumeric: "tabular-nums" as const,
  },
  yunxiaoList: {
    flex: 1,
    overflowY: "auto" as const,
    padding: "10px 18px 20px",
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
  },
  yunxiaoIssueCard: {
    display: "flex",
    alignItems: "flex-start" as const,
    gap: 10,
    padding: "10px 12px",
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    borderRadius: 10,
    transition: "border-color 0.12s, background 0.12s",
  },
  yunxiaoIssueCardHover: {
    display: "flex",
    alignItems: "flex-start" as const,
    gap: 10,
    padding: "10px 12px",
    background: "var(--bg-hover)",
    border: "1px solid var(--border-medium)",
    borderRadius: 10,
    transition: "border-color 0.12s, background 0.12s",
  },
  yunxiaoIssueSerial: {
    flexShrink: 0,
    fontSize: 11,
    fontWeight: 700,
    color: "var(--accent)",
    fontFamily: "var(--font-mono, monospace)",
    marginTop: 1,
  },
  yunxiaoIssueBody: {
    flex: 1,
    minWidth: 0,
  },
  yunxiaoIssueSubject: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    lineHeight: 1.4,
  },
  yunxiaoIssueMeta: {
    marginTop: 5,
    fontSize: 11.5,
    color: "var(--text-muted)",
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
    flexWrap: "wrap" as const,
  },
  yunxiaoMetaBadge: {
    padding: "1px 7px",
    borderRadius: 999,
    background: "var(--bg-elevated, var(--bg-hover))",
    color: "var(--text-secondary)",
    fontSize: 10.5,
    fontWeight: 600,
  },
  yunxiaoImportBtn: {
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center" as const,
    gap: 5,
    padding: "5px 12px",
    borderRadius: 7,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-card)",
    color: "var(--text-primary)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    transition: "background 0.12s, border-color 0.12s",
  },
  yunxiaoImportBtnHover: {
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center" as const,
    gap: 5,
    padding: "5px 12px",
    borderRadius: 7,
    border: "1px solid var(--accent)",
    background: "var(--bg-hover)",
    color: "var(--text-primary)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    transition: "background 0.12s, border-color 0.12s",
  },
  yunxiaoImportedBadge: {
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center" as const,
    gap: 5,
    padding: "5px 12px",
    borderRadius: 7,
    fontSize: 12,
    color: "var(--text-hint)",
    fontWeight: 500,
  },
  yunxiaoEmpty: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    padding: "48px 24px",
    color: "var(--text-muted)",
    fontSize: 13,
    textAlign: "center" as const,
    gap: 10,
  },
  yunxiaoLoadMore: {
    display: "inline-flex",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    gap: 6,
    padding: "8px 14px",
    borderRadius: 8,
    border: "1px solid var(--border-dim)",
    background: "transparent",
    color: "var(--accent)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    transition: "background 0.12s",
  },
  yunxiaoConnect: {
    flex: 1,
    display: "flex",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    padding: 24,
    overflowY: "auto" as const,
  },
  yunxiaoConnectCard: {
    width: 520,
    maxWidth: "100%",
    display: "flex",
    flexDirection: "column" as const,
    gap: 14,
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    borderRadius: 12,
    padding: "20px 22px",
    boxShadow: "var(--shadow-sm)",
  },
  yunxiaoConnectTitle: {
    fontSize: 15,
    fontWeight: 700,
    color: "var(--text-primary)",
  },
  yunxiaoHint: {
    fontSize: 11.5,
    color: "var(--text-hint)",
    lineHeight: 1.5,
  },
  yunxiaoField: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 5,
  },
  yunxiaoFieldLabel: {
    fontSize: 11.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
  },
  yunxiaoInput: {
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "var(--bg-elevated, var(--bg-panel))",
    color: "var(--text-primary)",
    padding: "8px 10px",
    fontSize: 13,
    outline: "none",
    fontFamily: "var(--font-mono, monospace)",
  },
  yunxiaoFieldRow: {
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
  },
  yunxiaoPrimaryBtn: {
    ...yunxiaoPrimaryBtnBase,
  },
  yunxiaoPrimaryBtnHover: {
    ...yunxiaoPrimaryBtnBase,
    background: "var(--bg-hover)",
    borderColor: "var(--accent)",
  },
  yunxiaoPrimaryBtnDisabled: {
    ...yunxiaoPrimaryBtnBase,
    opacity: 0.5,
    cursor: "default",
    pointerEvents: "none" as const,
  },
  yunxiaoSpinner: {
    color: "var(--text-hint)",
    flexShrink: 0,
  },
  // ── 议题详情页（v2） ─────────────────────────────────────────────
  yunxiaoDetailPane: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
    background: "var(--bg-panel)",
  },
  yunxiaoDetailBody: {
    flex: 1,
    overflowY: "auto" as const,
    padding: "14px 18px 24px",
    display: "flex",
    flexDirection: "column" as const,
    gap: 14,
  },
  yunxiaoDetailSection: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    borderRadius: 12,
    padding: "16px 18px",
  },
  yunxiaoDetailSectionTitle: {
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
    fontSize: 13,
    fontWeight: 700,
    color: "var(--text-primary)",
  },
  yunxiaoDetailSectionHint: {
    marginTop: 3,
    fontSize: 11.5,
    color: "var(--text-hint)",
    lineHeight: 1.5,
  },
  yunxiaoDetailMetaRow: {
    marginTop: 8,
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
    flexWrap: "wrap" as const,
    fontSize: 11.5,
    color: "var(--text-muted)",
  },
  yunxiaoDetailError: {
    marginTop: 8,
    fontSize: 12,
    color: "var(--danger)",
    lineHeight: 1.5,
  },
  yunxiaoFormFields: {
    marginTop: 12,
    display: "flex",
    flexDirection: "column" as const,
    gap: 10,
  },
  yunxiaoFormField: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 5,
  },
  yunxiaoFormFieldLabel: {
    fontSize: 11.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
  },
  yunxiaoFormInput: {
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "var(--bg-elevated, var(--bg-panel))",
    color: "var(--text-primary)",
    padding: "8px 10px",
    fontSize: 13,
    outline: "none",
    fontFamily: "var(--font-ui)",
    resize: "vertical" as const,
    minHeight: 38,
  },
  yunxiaoFormTextarea: {
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "var(--bg-elevated, var(--bg-panel))",
    color: "var(--text-primary)",
    padding: "8px 10px",
    fontSize: 12.5,
    lineHeight: 1.6,
    outline: "none",
    fontFamily: "var(--font-ui)",
    resize: "vertical" as const,
    minHeight: 64,
  },
  yunxiaoMentionAnchor: {
    position: "relative" as const,
  },
  yunxiaoFormActions: {
    marginTop: 12,
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
    flexWrap: "wrap" as const,
  },
  yunxiaoGhostBtn: {
    display: "inline-flex",
    alignItems: "center" as const,
    gap: 6,
    height: 30,
    padding: "0 12px",
    borderRadius: 8,
    border: "1px solid var(--border-medium)",
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    transition: "background 0.12s, border-color 0.12s",
  },
  yunxiaoGhostBtnDisabled: {
    display: "inline-flex",
    alignItems: "center" as const,
    gap: 6,
    height: 30,
    padding: "0 12px",
    borderRadius: 8,
    border: "1px solid var(--border-dim)",
    background: "transparent",
    color: "var(--text-hint)",
    fontSize: 12,
    fontWeight: 600,
    opacity: 0.55,
    cursor: "default",
    pointerEvents: "none" as const,
  },
  yunxiaoAgentBadge: {
    display: "inline-flex",
    alignItems: "center" as const,
    gap: 5,
    padding: "4px 10px",
    borderRadius: 999,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-elevated, var(--bg-card))",
    color: "var(--text-primary)",
    fontSize: 11.5,
    fontWeight: 600,
    cursor: "pointer",
    transition: "border-color 0.12s",
  },
  yunxiaoSkillBadge: {
    display: "inline-flex",
    alignItems: "center" as const,
    padding: "4px 10px",
    borderRadius: 999,
    background: "var(--bg-hover)",
    color: "var(--text-secondary)",
    fontSize: 11,
    fontWeight: 600,
    fontFamily: "var(--font-mono, monospace)",
  },
  // ── V3：回写云效 + 议题图片提示 ──────────────────────────────────
  yunxiaoWritebackBtn: {
    display: "inline-flex",
    alignItems: "center" as const,
    gap: 6,
    height: 28,
    padding: "0 12px",
    borderRadius: 7,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-card)",
    color: "var(--accent)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    flexShrink: 0,
    transition: "background 0.12s, border-color 0.12s, opacity 0.12s",
  },
  yunxiaoWritebackBtnDisabled: {
    display: "inline-flex",
    alignItems: "center" as const,
    gap: 6,
    height: 28,
    padding: "0 12px",
    borderRadius: 7,
    border: "1px solid var(--border-dim)",
    background: "transparent",
    color: "var(--text-hint)",
    fontSize: 12,
    fontWeight: 600,
    flexShrink: 0,
    opacity: 0.7,
    cursor: "default",
    pointerEvents: "none" as const,
  },
  yunxiaoWritebackBadge: {
    display: "inline-flex",
    alignItems: "center" as const,
    gap: 4,
    padding: "1px 7px",
    borderRadius: 999,
    background: "var(--bg-elevated, var(--bg-hover))",
    color: "var(--warning, #d97706)",
    fontSize: 10.5,
    fontWeight: 700,
    flexShrink: 0,
  },
  yunxiaoWritebackBadgeDone: {
    display: "inline-flex",
    alignItems: "center" as const,
    gap: 4,
    padding: "1px 7px",
    borderRadius: 999,
    background: "var(--bg-elevated, var(--bg-hover))",
    color: "var(--color-success, #16a34a)",
    fontSize: 10.5,
    fontWeight: 700,
    flexShrink: 0,
  },
  yunxiaoImageHint: {
    marginTop: 6,
    fontSize: 11.5,
    color: "var(--text-hint)",
    lineHeight: 1.5,
  },
  yunxiaoImageHintWarn: {
    marginTop: 6,
    fontSize: 11.5,
    color: "var(--warning, #d97706)",
    lineHeight: 1.5,
  },
  yunxiaoWritebackBackdrop: {
    position: "fixed" as const,
    inset: 0,
    display: "flex",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    background: "rgba(0, 0, 0, 0.45)",
    zIndex: 10000,
  },
  yunxiaoWritebackDialog: {
    width: 640,
    maxWidth: "calc(100vw - 48px)",
    maxHeight: "calc(100vh - 96px)",
    display: "flex",
    flexDirection: "column" as const,
    gap: 12,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 12,
    padding: "18px 20px",
    boxShadow: "var(--shadow-lg)",
  },
  yunxiaoWritebackTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: "var(--text-primary)",
  },
  yunxiaoWritebackHint: {
    fontSize: 11.5,
    color: "var(--text-hint)",
    lineHeight: 1.5,
  },
  yunxiaoWritebackTextarea: {
    flex: 1,
    minHeight: 220,
    resize: "vertical" as const,
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "var(--bg-elevated, var(--bg-panel))",
    color: "var(--text-primary)",
    padding: "10px 12px",
    fontSize: 12.5,
    lineHeight: 1.7,
    outline: "none",
    fontFamily: "var(--font-ui)",
  },
  yunxiaoWritebackError: {
    fontSize: 12,
    color: "var(--danger)",
    lineHeight: 1.5,
    whiteSpace: "pre-wrap" as const,
  },
  yunxiaoWritebackActions: {
    display: "flex",
    alignItems: "center" as const,
    justifyContent: "flex-end" as const,
    gap: 8,
  },
  yunxiaoWritebackSecondaryBtn: {
    display: "inline-flex",
    alignItems: "center" as const,
    gap: 6,
    height: 30,
    padding: "0 12px",
    borderRadius: 8,
    border: "1px solid var(--border-medium)",
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    transition: "background 0.12s, border-color 0.12s",
  },
  yunxiaoWritebackPrimaryBtn: {
    display: "inline-flex",
    alignItems: "center" as const,
    gap: 6,
    height: 30,
    padding: "0 14px",
    borderRadius: 8,
    border: "1px solid var(--accent)",
    background: "var(--accent)",
    color: "var(--text-on-accent, #fff)",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    transition: "opacity 0.12s",
  },
  yunxiaoWritebackPrimaryBtnDisabled: {
    display: "inline-flex",
    alignItems: "center" as const,
    gap: 6,
    height: 30,
    padding: "0 14px",
    borderRadius: 8,
    border: "1px solid var(--border-dim)",
    background: "var(--bg-hover)",
    color: "var(--text-hint)",
    fontSize: 12,
    fontWeight: 700,
    opacity: 0.6,
    cursor: "default",
    pointerEvents: "none" as const,
  },
} satisfies Record<string, React.CSSProperties>;
